[lottery]
    num = [
        ["01", "07", "11", "23", "24", "29", "16"],
        ["05", "06", "12", "17", "24", "33", "09"],
        ["02", "06", "09", "17", "24", "32", "09"],
        ["02", "06", "09", "17", "24", "32", "12"],
    ]

